### ISSUE TITLE
[RESOLVIDO] Instalar múltiplas versões do php no ubuntu

### ISSUE THREAD

**Issue by erandirjunior** [PHPcomRapadura/Forum#10]
Preciso instalar duas versões do php no ubuntu, ex: PHP 7.1 e 5.3, mas sem utilizar docker ou vagrant.

**Comment by alefcastelo** [comment]
@fsoaresjunior Uma das opções é vc ter dois binários com nomes diferentes, exemplo: um binário com php53, e outro com php71, ai vc pode criar um script que vai ficar fazendo a troca dos php_mod nas configurações do apache, pra quando vc precisar uma versão diferente da atual ele faça a troca, pois é muito chato ter que ficar alterando sempre que precisa!

**Comment by dorianneto** [comment]
@fsoaresjunior não sei para qual ambiente é a sua necessidade, mas se for para ambiente local uma outra alternativa é utilizar os binários que o @alefcastelo mencionou para rodar o servidor embutido do php. Escrevi um post sobre isso http://dorianneto.com.br/tutorial/servidor-web-embutido-porque-eu-nao-te-usei-antes/

Você também pode utilizar algumas libs que façam o trabalho chato da troca das versões por você no respectivo servidor, como o phpfarm e phpenv. Escrevi um post sobre o phpfarm onde detalho a instalação e utilização http://dorianneto.com.br/php/problemas-com-versoes-do-php-nunca-mais/. Como já faz um tempinho que escrevi isso e pelo que vi o phpfarm foi descontinuado, sugiro que você dê uma olhada no phpenv pois ele é uma solução bem mais atual e estável.

Abraço!
