### ISSUE TITLE
[RESOLVIDO] Soma de intervalo de horários 

### ISSUE THREAD

**Issue by alissonsilvas** [PHPcomRapadura/Forum#11]
Galera estou precisando fazer uma soma de intervalo de horários, para saber o total de horas trabalhadas de um funcionário, mas não estou conseguindo raciocinar direto onde estou errando o que estou fazendo de errado, alguem pode me dá uma luz.

exemplo de como eu quero que fique:

![captura de tela de 2017-08-25 14-17-03](https://user-images.githubusercontent.com/5832077/29724988-f7a58aec-89a0-11e7-85ff-54fde1cf9f3a.png)

minha linha de raciocinio é essa:

`
$time1 = new DateTime('08:00:00');
$time2 = new DateTime('12:00:00');
			
$time3 = new DateTime('13:00:00');
$time4 = new DateTime('17:00:00');
			
$diff1 = $time2->diff($time1);
$hss1 = $diff1->format('%h:%i:%s');
			
$diff2 = $time4->diff($time3);
$hss2 = $diff2->format('%h:%i:%s');

$hscont = $hss2->diff($hss1);
			
echo $hscont;`

**Comment by dorianneto** [comment]
O raciocínio ta certo, só a execução que ta errada.

Tu não vai conseguir calcular a diferença entre `$hss2` e `$hss1` invocando o método **diff** pelo fato de que o valor das 2 variávels é uma string. Mesmo que tu não utilizasse o método **format**, ia dar pau do mesmo jeito pois o retorno do método **diff** é um valor do tipo `DateInterval` que não tem o método **diff**.

Uma solução seria após calcular as diferenças entre os horários, somar os resultados através de uma outra instância onde tu vai conseguir ter acesso aos métodos necessários para manipular as diferenças calculadas.

Ex:

```
<?php
$a = new DateTime('08:00:00');
$b = new DateTime('12:10:00');
$interval1 = $a->diff($b);
echo "interval 1: ", $interval1->format("%H:%I"), "\n";

$c = new DateTime('14:00:00');
$d = new DateTime('18:30:00');
$interval2 = $c->diff($d);
echo "interval 2: ", $interval2->format("%H:%I"), "\n";

$e = new DateTime('00:00');
$f = clone $e;
$e->add($interval1);
$e->add($interval2);
echo "Total interval : ", $f->diff($e)->format("%H:%I"), "\n";
```
https://stackoverflow.com/questions/11556731/how-we-can-add-two-date-intervals-in-php

**Comment by alissonsilvas** [comment]
puts cara é isso mesmo vlw aew!
