### ISSUE TITLE
Conexão Doctrine e PostgrSQL

### ISSUE THREAD

**Issue by ghost** [PHPcomRapadura/Forum#13]
Estou com dificuldade para fazer a conexão com o PostgreSQL, esta dando o seguinte erro: 

`Fatal error: Uncaught PDOException: SQLSTATE[08006] [7] could not connect to server: Arquivo ou diretório não encontrado Is the server running locally and accepting connections on Unix domain socket "/tmp/.s.PGSQL.5432"? in /home/jholdy/PhpstormProjects/jholdy-mvc/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43 Stack trace: #0 /home/jholdy/PhpstormProjects/jholdy-mvc/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('pgsql:dbname=im...', 'postgres', 'usuario_db', Array) #1 /home/jholdy/PhpstormProjects/jholdy-mvc/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('pgsql:dbname=im...', 'postgres', 'sua_senha', Array) #2 /home/jholdy/PhpstormProjects/jholdy-mvc/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(372): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'postgres', 'sua_senha', Array) #3 /home/jholdy/PhpstormProjects/jholdy-mvc/vendor/doctrine/dbal/lib/Doctrine/DBAL/Co in /home/jholdy/PhpstormProjects/jholdy-mvc/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php on line 89`

Já achei a seguinte solução:

/**
         * Se for PostgreSQL faça e estiver no ubuntu ou Debian:
         *
         *  - Link simbólico para colocar o socket na pasta /tmp
         *      sudo ln -s /var/run/postgresql/.s.PGSQL.5432 /tmp/
         *
         *  - Trocar peer por md5 no arquivo pg_hba.conf
         *      sudo gedit /etc/postgresql/9.5/main/pg_hba.conf
         *
         *  - Restartar o PostgreSQL
         *      sudo service postgresql restart
         *
         */

 Mas mesmo assim toda vida que inicio o sistema, ainda tenho que fazer o Link simbólico para colocar o socket na pasta /tmp
Como devo proceder para não ter que fazer isso sempre, ou se existe uma melhor solução além dessa acima?

O projeto esta no git: https://github.com/jholdy/jholdy-mvc

**Comment by marcialwushu** [comment]
Doctrine PHP Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found

...I figured out what the problem was, for anyone encountering the same error. In my bootstrap.php, I was retrieving data from the table using the Entity Manager ($eventRepository = $entityManager->getRepository('Event') for example). Removing this code made the command execute correctly.

<https://stackoverflow.com/questions/48928021/doctrine-php-fatal-error-uncaught-pdoexception-sqlstate42s02-base-table-or>
