### ISSUE TITLE
[OFF] Ionic 2 - Gravar áudio

### ISSUE THREAD

**Issue by dersonsena** [PHPcomRapadura/Forum#4]
Fala galera! Alguém aqui já implementou a parte de `Media` do Ionic Native ? Eu implementei aqui em um app seguindo a documentação e deu tudo certinho, gravou o audio e salva no device de boa.

Eu percebi que ele salva dentro de `/storage/emulated/0/Android/data/br.com.vialist/files/audio.3gp` (isso no Android). Mas vi que o Whatsapp, por exemplo, tem uma pasta com a sua estrutura de medias. Nesse caso, eu teria que criar uma pasta do meu App, fazer o processo de copiar/mover a mídia para ele ?

**Comment by alefcastelo** [comment]
Essa issue foi resolvida @dersonsena ?

**Comment by alefcastelo** [comment]
Essa issue foi resolvida @dersonsena ?
