### ISSUE TITLE
[RESOLVIDO] PHP não copia conteudo de arquivo CSV com acentuação para o banco de dados

### ISSUE THREAD

**Issue by pensadorce** [PHPcomRapadura/Forum#5]
bom dia galera, to com um problema estranho, criei um arquivo em php que lê o arquivo csv e o copia para dentro do banco de dados mysql, so que as linhas onde contem informação com acentuação ele não copia para base, abaixo segue as linhas de comando que estou usando.
$handle = fopen('cmibi/empenho.csv', 'r');
$pointer = fgetcsv($handle, 0, ';', '"');

/// Comandos usados
$con = new PDO("mysql:host=localhost;dbname=portal", 'root', '', array(PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8'));

while ($pointer = fgetcsv($handle, 0, ';', '"')) {
    $sql = "INSERT INTO ss_empenho (`ssinfo_id`, `ssinfo_gestor`, `ssinfo_data`, `ssinfo_doc_caixa`, `ssinfo_credor`, `ssinfo_cpfcnpj`, `ssinfo_valor`) VALUES (NULL,'$pointer[0]','$pointer[1]','$pointer[2]','$pointer[3]','$pointer[4]','$pointer[5]')";
    
    $stmt = $con->prepare($sql);
    $stmt->bindParam(':id', $pointer[0], PDO::PARAM_INT);
    $stmt->bindParam(':value2', $pointer[1], PDO::PARAM_STR);
    $stmt->bindParam(':value3', $pointer[2], PDO::PARAM_STR);
    $stmt->bindParam(':value4', $pointer[3], PDO::PARAM_STR);
    $stmt->bindParam(':value5', $pointer[4], PDO::PARAM_STR);
    $stmt->bindParam(':value6', $pointer[5], PDO::PARAM_STR);
    $stmt->bindParam(':value7', $pointer[6], PDO::PARAM_INT);
///
ele copia os arquivos para a base, menos os que tem acentuação, abaixo alguns exemplos do arquivo
CMI;04/01/2016;04.01.0003;FOLHA DE PAGAMENTO - EFETIVOS;06.577.605/0001-26;57.000,00
CMI;04/01/2016;04.01.0004;TELEMAR NORTE LESTE S/A;33.000.118/0015-74;7.200,00
CMI;04/01/2016;04.01.0005;COELCE - COMPANHIA ENERGETICA DO CEARÁ;07.047.251/0001-70;3.800,00 <== neste aqui tem acento no ceará, ai ele nao copia para o banco.

**Comment by wilcorrea** [comment]
Tenta usar utf8_encode/ut8_decode para poder tratar os itens que são textos

**Comment by WalderlanSena** [comment]
Ou então seta na query de conexão:

$con = new \PDO("mysql:host=$host;dbname=$dbname;charset=$charset",$user,$pass);
$con->setAttribute(\PDO::MYSQL_ATTR_INIT_COMMAND,"SET NAMES '$charset' COLLATION '$collation'");

**Comment by pensadorce** [comment]
eu ja coloquei na parte de cima
$con = new PDO("mysql:host=localhost;dbname=portal", 'root', '', array(PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8'));

**Comment by pensadorce** [comment]
mais ainda ta dando esse erro

**Comment by pensadorce** [comment]
mudei para este 'SET NAMES Latin1' e deu blz, valew a ajuda de todos.
