### ISSUE TITLE
[RESOLVIDO] Auxilio para encontrar erro não detectado!

### ISSUE THREAD

**Issue by brunocs86** [PHPcomRapadura/Forum#7]
Boa tarde a todos,

Estou fazendo o curso do Alura de PHP e MYSQL  I, o qual aos poucos vai montando um sistema de informações de produtos, conclui a aula 10 que implementa a possibilidade de alterar informações dos produtos. O meu código não apresenta erro nenhum ao clicar o botão de alterar porém quando vou conferir vejo que as alterações não foram executadas. Segue link abaixo com o projecto.

https://github.com/brunocs86/Loja

**Comment by WalderlanSena** [comment]
Qual a estrutura do banco de dados ?

**Comment by brunocs86** [comment]
Eu não sei bem esses detalhes, pois sou iniciantes, mas consegui ajeitar o problema alterando meu arquivo banco-produto.php pelo respectivo arquivo do repositorio do alura.

**Comment by WalderlanSena** [comment]
OK. Tranquilo !

**Comment by Luitame** [comment]
Não vá por esse caminho jovem, talvez isso retarde seu aprendizado. São justamente com os problemas que nós desenvolvedores evoluímos. Que graça há num desenvolvedor `ctrl+c` `ctrl+v`? Ao menos tente entender aonde morava sua falha.

**Comment by WalderlanSena** [comment]
Isso mesmo, "É debugando que se aprende !"

**Comment by brunocs86** [comment]
Agradeço sua dica Luitame, entendo a importância do debug, porém estava ansioso para 'solucionar' o problema, tentarei me esforçar mais da próxima.
