### ISSUE TITLE
[RESOLVIDO] Sugestões de palestras para o próximo encontro de dev's

### ISSUE THREAD

**Issue by alefcastelo** [PHPcomRapadura/Forum#8]
Galera os representantes entraram em acordo e concordaram com a ideia de dar a oportunidade de todos os membros comentarem sobre o que gostaria de assistir no próximo encontro de dev's.

Deixem registrado aqui nos comentarios as suas sugestões de palestras e uma breve descrição porquer você gostaria de que ela fosse escolhida.

Lembrando que para cada sugestão pode não existir palestras submetidas e que queremos colher informações para melhorar nosso criterio de escolha.

Abraço a todos os membros.

**Comment by alissonsilvas** [comment]
@alefcastelo Testes, e debugs. 
Exemplos de usos de ferramentas: selenium, xdebug e etc.

**Comment by thiagodionizio** [comment]
@alefcastelo Não conseguiremos alguém da jetbrains pra dar alguma palestras?

**Comment by alefcastelo** [comment]
@thiagodionizio eu não conheço ninguém daqui do estado, a sua sugestão seria algo relacionado ao PHPStorm?

**Comment by thiagodionizio** [comment]
@alefcastelo Sim, poderíamos tentar entrar em contato com alguem de lá

**Comment by alefcastelo** [comment]
@thiagodionizio o ideal é que os palestrantes sejam locais, pois nivel dos nosso encontros são locais. Mais internamente vamos anotar usa sugestão, se puder descrever melhor sobre o q você gostaria de entendar dentro do PHPStorm seria legal, pode ser que alguém veja a sugestão e submeta alguma talk sobre ela!

**Comment by Luitame** [comment]
@alefcastelo seria massa algo relacionado a **arquitetar aplicações**. Algum conteúdo relaciona tipo a  **DDD**. Pois, ao meu ver é umas das fases mais difíceis de todo projeto. E inclusive em ferramentas como Zend, Symfony que nativamente trabalham com módulos como separar sua aplicação por contexto etc etc. Outra parada massa seria alguma talk que tocasse no ponto de aplicações de alta disponibilidade.

**Comment by alefcastelo** [comment]
@Luitame boa sugestão, anotado!

**Comment by dersonsena** [comment]
@alefcastelo Gostei da sugestão do @Luitame ! Algo sobre DDD menos teórico e mais prático seria uma ótima sugestão

**Comment by erandirjunior** [comment]
@thiagodionizio Conceitos Solid, importância de padrões no desenvolvimento, docker, laravel, webservice...

**Comment by alefcastelo** [comment]
Mais sugestões para nosso próximo encontro ?

**Comment by alefcastelo** [comment]
Mais sugestões para nosso próximo encontro ?

**Comment by ital0** [comment]
não seria um assunto em específico, mas algo que aborde frameworks que não são muito usados aqui no Brasil, como ZF3 e/ou Symfony.

**Comment by alefcastelo** [comment]
Passando aqui pra movimentar, mais sugestões para nosso próximo encontro ?

**Comment by alefcastelo** [comment]
Sugestões?
